server:
  port: 8080
  
spring.datasource:
  url: jdbc:mysql://localhost:32769/sample?useSSL=false
  username: sample
  password: sample
  
spring.data.rest.base-path: /api

spring.jpa.properties:
  hibernate.show_sql: true
  hibernate.use_sql_comments: true
  hibernate.format_sql: true
